version: '3.1'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    links:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - app-network
  app:
    image: transactionapp
    ports: 
      - "5055:5055"
    environment:
      APP_ENV: prod 
    networks:
      - app-network
    links:
      - redis
      - mongo

networks: 
    app-network:
      driver: bridge